-- creates a database
-- if database exist, script should not fail
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

-- create a table in database
-- id INT, autogenerated, cant be null is a primary key
-- name VARCHAR(256), cant be NULL
-- if table exist, script should not fail
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states
(
	id INT UNIQUE AUTO_INCREMENT NOT NULL,
	name VARCHAR(256) NOT NULL,
	PRIMARY KEY (id)
);